In [ ]:
#Task:1
#Create this student DataFrame:
import pandas as pd

data ={
    "Name": ["Ali", "Sara", "Ahmed","Ayesha", "Zain"],
    "Marks" : [70, 85, 60, 95, 45]
}
df = pd.DataFrame(data)
print(df)
Marks=df["Marks"]
print(Marks.mean())
print(Marks.max())
print(Marks.min())



name =df["Name"]
print(name.count())

     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
4    Zain     45
71.0
95
45
5

In [ ]:
passed_students = df[df["Marks"] >= 50]
print("Passed Students:")
print(passed_students)

failed_students = df[df["Marks"] < 50]
print("Failed Students:")
print(failed_students)

Passed Students:
     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
Failed Students:
   Name  Marks
4  Zain     45

In [ ]:
df["cities"]=["karachi","lahore","faisalabad","islamabad","rawalpindi"]
print("only karachi students:")
print(df[df['cities'] == "karachi"])

only karachi students:
  Name  Marks   cities
0  Ali     70  karachi

In [ ]:
#Task:4

data = {


    "Name":["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Course":["AI", "Web", "AI", "Web","AI"],
    "Marks":[70, 85, 60, 95, 45]
}
df = pd.DataFrame(data)
result=df.groupby("Course")["Marks"].mean()
print(result)

Course
AI     58.333333
Web    90.000000
Name: Marks, dtype: float64

In [ ]:
#Task:5
import pandas as pd
data = {
    "Name": ["Ali","Sara","Ahmed","Ayesha","Zain"],
    "Marks": [80,None,70,None,90]


}
df = pd.DataFrame(data)


print(df.isnull())
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
print(df)

    Name  Marks
0  False  False
1  False   True
2  False  False
3  False   True
4  False  False
     Name  Marks
0     Ali   80.0
1    Sara   80.0
2   Ahmed   70.0
3  Ayesha   80.0
4    Zain   90.0

In [ ]:
import pandas as pd

data = {
    "Name": ["Ali", "Hamnah", "Hassnain", "Zara", "Ayan", "Khadija", "Lamisa", "Hala", "Qirat", "Shifa"],
    "Age": [5, 9, 12, 14, 11, 12, 15, 17, 11, 20],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
    "City": ["Karachi", "Lahore", "Islamabad", "Peshawar", "Karachi", "Lahore", "Islamabad", "Peshawar", "Karachi", "Lahore"]
}


df = pd.DataFrame(data)

(df)

       Name  Age  Gender       City
0       Ali    5    Male    Karachi
1    Hamnah    9  Female     Lahore
2  Hassnain   12    Male  Islamabad
3      Zara   14  Female   Peshawar
4      Ayan   11    Male    Karachi
5   Khadija   12  Female     Lahore
6    Lamisa   15    Male  Islamabad
7      Hala   17  Female   Peshawar
8     Qirat   11    Male    Karachi
9     Shifa   20  Female     Lahore

In [ ]:
(df.head(4))

       Name  Age  Gender       City
0       Ali    5    Male    Karachi
1    Hamnah    9  Female     Lahore
2  Hassnain   12    Male  Islamabad
3      Zara   14  Female   Peshawar

In [ ]:
(df.tail(4))

     Name  Age  Gender       City
6  Lamisa   15    Male  Islamabad
7    Hala   17  Female   Peshawar
8   Qirat   11    Male    Karachi
9   Shifa   20  Female     Lahore

In [ ]:
df.shape

(10, 4)

In [ ]:
df.describe()

             Age
count  10.000000
mean   12.600000
std     4.195235
min     5.000000
25%    11.000000
50%    12.000000
75%    14.750000
max    20.000000

In [ ]:
df["Age"]

0     5
1     9
2    12
3    14
4    11
5    12
6    15
7    17
8    11
9    20
Name: Age, dtype: int64

In [ ]:
df["Gender"]

0      Male
1    Female
2      Male
3    Female
4      Male
5    Female
6      Male
7    Female
8      Male
9    Female
Name: Gender, dtype: object

In [ ]:
df[["Age", "Gender"]]

   Age  Gender
0    5    Male
1    9  Female
2   12    Male
3   14  Female
4   11    Male
5   12  Female
6   15    Male
7   17  Female
8   11    Male
9   20  Female

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   Gender  10 non-null     object
 3   City    10 non-null     object
dtypes: int64(1), object(3)
memory usage: 452.0+ bytes

In [ ]:
df.loc[5, ["Gender"]]

Gender    Female
Name: 5, dtype: object

In [ ]:
df.iloc[[0,5]]

      Name  Age  Gender     City
0      Ali    5    Male  Karachi
5  Khadija   12  Female   Lahore

In [ ]:
df.iloc[5,3]

'Lahore'

In [ ]:
df[df ["Gender"] == "Female"]

      Name  Age  Gender      City
1   Hamnah    9  Female    Lahore
3     Zara   14  Female  Peshawar
5  Khadija   12  Female    Lahore
7     Hala   17  Female  Peshawar
9    Shifa   20  Female    Lahore

In [ ]:
df[df ["City"] == "Karachi"]

    Name  Age Gender     City
0    Ali    5   Male  Karachi
4   Ayan   11   Male  Karachi
8  Qirat   11   Male  Karachi

In [ ]:
#Deleting column
df =df.drop("Age", axis=1, errors='ignore')
df

       Name  Gender       City
0       Ali    Male    Karachi
1    Hamnah  Female     Lahore
2  Hassnain    Male  Islamabad
3      Zara  Female   Peshawar
4      Ayan    Male    Karachi
5   Khadija  Female     Lahore
6    Lamisa    Male  Islamabad
7      Hala  Female   Peshawar
8     Qirat    Male    Karachi
9     Shifa  Female     Lahore

In [ ]:
#Adding a new column
df["Salary"] = [20, 22, 21, 19, 23, 20, 22, 18, 21, 20]
df

       Name  Age  Gender       City  Salary
0       Ali    5    Male    Karachi      20
1    Hamnah    9  Female     Lahore      22
2  Hassnain   12    Male  Islamabad      21
3      Zara   14  Female   Peshawar      19
4      Ayan   11    Male    Karachi      23
5   Khadija   12  Female     Lahore      20
6    Lamisa   15  Female  Islamabad      22
7      Hala   17  Female   Peshawar      18
8     Qirat   11  Female    Karachi      21
9     Shifa   20  Female     Lahore      20

In [ ]:
df["Bonus Salary"] = df["Salary"] + 1
df

       Name  Age  Gender       City  Salary  Bonus Salary
0       Ali    5    Male    Karachi      20            21
1    Hamnah    9  Female     Lahore      22            23
2  Hassnain   12    Male  Islamabad      21            22
3      Zara   14  Female   Peshawar      19            20
4      Ayan   11    Male    Karachi      23            24
5   Khadija   12  Female     Lahore      20            21
6    Lamisa   15  Female  Islamabad      22            23
7      Hala   17  Female   Peshawar      18            19
8     Qirat   11  Female    Karachi      21            22
9     Shifa   20  Female     Lahore      20            21

In [ ]:
df = df.drop(3, axis=0, errors='ignore')
df

       Name  Gender       City  Salary
0       Ali    Male    Karachi      20
1    Hamnah  Female     Lahore      22
2  Hassnain    Male  Islamabad      21
4      Ayan    Male    Karachi      23
5   Khadija  Female     Lahore      20
6    Lamisa    Male  Islamabad      22
7      Hala  Female   Peshawar      18
8     Qirat    Male    Karachi      21
9     Shifa  Female     Lahore      20

In [ ]:
df.loc[6, "Gender"] = None
df

       Name  Gender       City  Salary
0       Ali    Male    Karachi      20
1    Hamnah  Female     Lahore      22
2  Hassnain    Male  Islamabad      21
4      Ayan    Male    Karachi      23
5   Khadija  Female     Lahore      20
6    Lamisa    None  Islamabad      22
7      Hala  Female   Peshawar      18
8     Qirat    Male    Karachi      21
9     Shifa  Female     Lahore      20

In [ ]:
df.isnull()

    Name  Gender   City  Salary
0  False   False  False   False
1  False   False  False   False
2  False   False  False   False
4  False   False  False   False
5  False   False  False   False
6  False    True  False   False
7  False   False  False   False
8  False   False  False   False
9  False   False  False   False

In [ ]:
df.isnull().sum()

Name      0
Gender    1
City      0
Salary    0
dtype: int64

In [ ]:
df.dropna()

       Name  Gender       City  Salary
0       Ali    Male    Karachi      20
1    Hamnah  Female     Lahore      22
2  Hassnain    Male  Islamabad      21
4      Ayan    Male    Karachi      23
5   Khadija  Female     Lahore      20
7      Hala  Female   Peshawar      18
8     Qirat    Male    Karachi      21
9     Shifa  Female     Lahore      20

In [ ]:
df.fillna("Female")

       Name  Gender       City  Salary
0       Ali    Male    Karachi      20
1    Hamnah  Female     Lahore      22
2  Hassnain    Male  Islamabad      21
4      Ayan    Male    Karachi      23
5   Khadija  Female     Lahore      20
6    Lamisa  Female  Islamabad      22
7      Hala  Female   Peshawar      18
8     Qirat    Male    Karachi      21
9     Shifa  Female     Lahore      20

In [ ]:
df["Gender"] = df["Gender"].fillna("Female")
df

       Name  Gender       City  Salary
0       Ali    Male    Karachi      20
1    Hamnah  Female     Lahore      22
2  Hassnain    Male  Islamabad      21
4      Ayan    Male    Karachi      23
5   Khadija  Female     Lahore      20
6    Lamisa  Female  Islamabad      22
7      Hala  Female   Peshawar      18
8     Qirat    Male    Karachi      21
9     Shifa  Female     Lahore      20

In [ ]:
df.duplicated()

0    False
1    False
2    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates()

       Name  Gender       City  Salary
0       Ali    Male    Karachi      20
1    Hamnah  Female     Lahore      22
2  Hassnain    Male  Islamabad      21
4      Ayan    Male    Karachi      23
5   Khadija  Female     Lahore      20
6    Lamisa  Female  Islamabad      22
7      Hala  Female   Peshawar      18
8     Qirat    Male    Karachi      21
9     Shifa  Female     Lahore      20

In [ ]:
df.sort_values("City")

       Name  Gender       City  Salary
2  Hassnain    Male  Islamabad      21
6    Lamisa  Female  Islamabad      22
0       Ali    Male    Karachi      20
4      Ayan    Male    Karachi      23
8     Qirat    Male    Karachi      21
1    Hamnah  Female     Lahore      22
5   Khadija  Female     Lahore      20
9     Shifa  Female     Lahore      20
7      Hala  Female   Peshawar      18

In [ ]:
df.sort_values("City", ascending=False)

       Name  Gender       City  Salary
7      Hala  Female   Peshawar      18
1    Hamnah  Female     Lahore      22
5   Khadija  Female     Lahore      20
9     Shifa  Female     Lahore      20
0       Ali    Male    Karachi      20
4      Ayan    Male    Karachi      23
8     Qirat    Male    Karachi      21
2  Hassnain    Male  Islamabad      21
6    Lamisa  Female  Islamabad      22

In [ ]:
df.groupby("City")["Name"].count()

City
Islamabad    2
Karachi      3
Lahore       3
Peshawar     1
Name: Name, dtype: int64

In [ ]:
import pandas as pd

data = {
    "Name": ["Ali", "Hamnah", "Hassnain", "Zara", "Ayan", "Khadija", "Lamisa", "Hala", "Qirat", "Shifa"],
    "Age": [5, 9, 12, 14, 11, 12, 15, 17, 11, 20],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Female", "Female", "Female", "Female"],
    "City": ["Karachi", "Lahore", "Islamabad", "Peshawar", "Karachi", "Lahore", "Islamabad", "Peshawar", "Karachi", "Lahore"]
}

df = pd.DataFrame(data)
df

       Name  Age  Gender       City
0       Ali    5    Male    Karachi
1    Hamnah    9  Female     Lahore
2  Hassnain   12    Male  Islamabad
3      Zara   14  Female   Peshawar
4      Ayan   11    Male    Karachi
5   Khadija   12  Female     Lahore
6    Lamisa   15  Female  Islamabad
7      Hala   17  Female   Peshawar
8     Qirat   11  Female    Karachi
9     Shifa   20  Female     Lahore

In [ ]:
df.groupby("City")["Age"].mean()

City
Islamabad    13.500000
Karachi       9.000000
Lahore       13.666667
Peshawar     15.500000
Name: Age, dtype: float64

In [ ]:
df.groupby("City")["Age"].count()

City
Islamabad    2
Karachi      3
Lahore       3
Peshawar     2
Name: Age, dtype: int64

In [ ]:
df.groupby("City")["Age"].sum()

City
Islamabad    27
Karachi      27
Lahore       41
Peshawar     31
Name: Age, dtype: int64

In [ ]:
df1 = {
    "Name": ["Maha", "Isra"],
    "Age" : [29, 39],
    "Gender": ["Female", "Female"],
    "City": ["Karachi", "Lahore"]
}


df2 = {
    "Name": ["Shiza", "Fiza", "Ali", "Areesha"],
    "Age": [22, 55, 55, 77],
    "Gender": ["Female", "Female", "Male", "Female"],
    "City": ["Karachi", "Lahore", "Islamabad", "Peshawar"]
}

df1 = pd.DataFrame(df1)
df2 = pd.DataFrame(df2)

combined_df = pd.concat([df1, df2], ignore_index=True)
combined_df

      Name  Age  Gender       City
0     Maha   29  Female    Karachi
1     Isra   39  Female     Lahore
2    Shiza   22  Female    Karachi
3     Fiza   55  Female     Lahore
4      Ali   55    Male  Islamabad
5  Areesha   77  Female   Peshawar